#yarnPath: .yarn/releases/yarn-4.8.1.cjs
#nodeLinker: pnp
#enableGlobalCache: false # 각 프로젝트 내의 .yarn/cache에 캐시 저장
#enableScripts: false # postinstall 스크립트의 실행을 막아 .yarn/unplugged 디렉토리를 생성하지 않도록

nodeLinker: node-modules

